### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lecueguillaume** [dunan/MultiVariatePointProcess#1]
Dear Nan Du,

I'm trying to install your library on MAC OS X Yosemite. I've X11 and gnuplot installed, I cloned your repos and try to install your library via 'make' but I got the following error message:

$ make
g++ -MMD -c -Wall -O3 -m64 -std=c++11 -I./include -I./3rd-party -o build/src/GNUPlotWrapper.o src/GNUPlotWrapper.cc
In file included from src/GNUPlotWrapper.cc:8:
src/../include/Utility.h:36:26: error: unknown type name 'FunctionHandler'
double SimpsonIntegral38(FunctionHandler& functor, double a, double b, u...
                         ^
1 error generated.
make: **\* [build/src/GNUPlotWrapper.o] Error 1

It would be very nice of you if you can tell me how to solve this issue. I'm very curious to see how your time-dependent recommendation system works.
Thanks,
Guillaume.

**Comment by dunan** [comment]
This is has been fixed by pushing the latest update.
