### ISSUE TITLE
Step should be reduced after generating the next point

### ISSUE THREAD

**Issue by emaadmanzoor** [dunan/MultiVariatePointProcess#3]
In the Ogata's thinning algorithm implementation, I believe that `step` is the interval of time for which the intensity upper bound is valid. When the current time `t` is incremented as `t = t + s`, shouldn't the time for which the upper bound is valid decrease as `step = step - s`?

   * https://github.com/dunan/MultiVariatePointProcess/blob/master/src/OgataThinning.cc#L47
   * https://github.com/dunan/MultiVariatePointProcess/blob/master/src/OgataThinning.cc#L77

**Comment by dunan** [comment]
Hi emaadmanzoor,

step_ is the how far we look forward into the future to have a valid upper bound on the intensity function, so that we can still sample from a monotonically increasing intensity function.

Nan

**Comment by emaadmanzoor** [comment]
I understand, but shouldn't `step_` be updated (reduced) after an event is generated and rejected?

For example, if `t = 0` and `step_ = 1` because the upper-bound is valid for the next one second. Then I sample `s = 0.2` from the upper-bound exponential distribution and I obtain `t = t + s = 0.2`. Let's say I reject this event. Now, shouldn't the upper-bound be valid only for the next `step_ - s = 0.8` seconds, since `0.2` seconds have elapsed?

**Comment by dunan** [comment]
if you reject the event, then t is updated to t = t + 1, and we restart from 1

**Comment by emaadmanzoor** [comment]
Looking at the rejection condition here: https://github.com/dunan/MultiVariatePointProcess/blob/master/src/OgataThinning.cc#L44-L49

Isn't it `t = t + s` on rejection (since `s = 0.2 < step_ = 1`)? Why would it be `t+1`? After rejection the upper bound is recomputed at `t + s` and this is again valid for the next `step_` seconds. What is the intuition behind that?

The reason I am curious is because I have a time-varying base intensity that depends on the hour of the day. Say at `t = 1600` my upper bound is valid for an hour. But if I reject at `t = 1630`, and I recompute the new upper bound, it is only valid for the next 30 minutes. So I had to add a `step_ -= s` right after rejection.

**Comment by dunan** [comment]
the intuition is that if the event at t + 0.2 is rejected, then it means that there is no event happening within the interval step_1, so we need to restart at t + step_.
